---
title: "Problem 2 in one dashboard"
output: 
  flexdashboard::flex_dashboard:
    code_folding: hide
    theme: journal
---

<a href="index.html" class="btn btn-primary">⬅ Back to Home</a>

```{r setup, include=FALSE}
# Load all required packages
library(flexdashboard)
library(plotly)
library(tidyverse)
library(p8105.datasets)

data("instacart") 

plot_1_data <- instacart %>%
  group_by(department) %>%
  summarize(total_sales = n()) %>%
  mutate(department = reorder(department, total_sales))

top_10_depts <- plot_1_data %>%
  arrange(desc(total_sales)) %>%
  slice(1:10) %>%
  pull(department)

plot_2_data <- instacart %>%
  filter(department %in% top_10_depts) %>%
  slice_sample(n = 10000) %>%
  mutate(department = factor(department, levels = top_10_depts))

plot_3_data <- instacart %>%
  filter(department == "snacks") %>%
  group_by(order_hour_of_day) %>%
  summarize(count_of_items = n()) %>%
  ungroup() %>%
  arrange(order_hour_of_day)
```

Column {data-width=400}
-----------------------------------------------------------------------

### First Plot: Total Items Sold by Department
```{r}
plot_ly(
  data = plot_1_data,
  y = ~department,
  x = ~total_sales,
  type = "bar",
  orientation = "h"
) %>% 
  layout(
    title = "Total Items Sold by Department",
    yaxis = list(title = "Department"),
    xaxis = list(title = "Total Items Sold")
  )
```

Column {data-width=400}
-----------------------------------------------------------------------

### Second Plot: Order Hour Distribution (Top 10 Depts)
```{r}
plot_ly(
  data = plot_2_data,
  x = ~department,
  y = ~order_hour_of_day, 
  type = "box",
  name = "Order Hour Distribution"
) %>% 
  layout(
    title = "Order Hour Distribution (Top 10 Depts)",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Hour of Day (0-23)")
  )
```

### Third Plot: Snack Item Orders by Hour of Day
```{r}
plot_ly(
  data = plot_3_data,
  x = ~order_hour_of_day,
  y = ~count_of_items,
  type = "scatter",
  mode = "lines+markers"
) %>%
  layout(
    title = "Snack Item Orders by Hour of Day",
    xaxis = list(
      title = "Hour of Day (0-23)",
      dtick = 1 
    ),
    yaxis = list(title = "Number of Snack Items Ordered")
  )
```